### ISSUE TITLE
Change "MultiOTP Login" Text

### ISSUE THREAD

**Issue by Jonathan-Garber** [multiOTP/multiOTPCredentialProvider#1]
How can we change the text showing on the logon screen "MultiOTP Login"
I am not seeing this in the config files or in registry.

**Comment by Jonathan-Garber** [comment]
Compiling my own credential provider to address this and some other things. Closing this issue.

**Comment by multiOTP** [comment]
Hello, thanks for your feedback. An additional optional registry entry will be setup in the future.

**Comment by Jonathan-Garber** [comment]
That is great news. Thanks.
