### ISSUE TITLE
multiOTP option is not visible on Logon UI

### ISSUE THREAD

**Issue by alisolutions** [multiOTP/multiOTPCredentialProvider#10]
Hi,

After completing the installation, I am unable to run the see the OTP Login user on Logon UI. Following are my detailed steps.
1. Installed multiOTP server
2. Create a user and verify it using Google Authenticator OTP
3. Then installed the multiOTP using your installed.
4. Activated The Credential Provider.
5. After restart I did not see any OTP logon UI.

Please let me know if I am doing anything wrong. I tested it on fresh installed windows 10 64bit on vmware.

![img_8636](https://user-images.githubusercontent.com/2880208/39243853-4912716c-48a8-11e8-8b6a-8605ca2508ea.jpg)
![img_8632](https://user-images.githubusercontent.com/2880208/39243868-50e4629c-48a8-11e8-9315-ffacb2e80060.jpg)
![img_8633](https://user-images.githubusercontent.com/2880208/39243869-51d502e2-48a8-11e8-960c-7a890b6df445.jpg)
![img_8634](https://user-images.githubusercontent.com/2880208/39243870-51ff3c4c-48a8-11e8-8751-1a37eadba93a.jpg)
![img_8635](https://user-images.githubusercontent.com/2880208/39243872-522b537c-48a8-11e8-864b-cbb92a927da1.jpg)

**Comment by alisolutions** [comment]
Ops, 
Only need to change following parameter in reg key .... :(
multiOTPRDPOnly -> 1

Its working without any issue.
Closing it now.

**Comment by multiOTP** [comment]
Yes, by default, as seen in the installer, only RDP access is protected.
You did the right change. You could also run again the installer, and it will allow you changes the options.
Regards,
