### ISSUE TITLE
Reinstallation of MS VC++ needed

### ISSUE THREAD

**Issue by yankaiqian** [multiOTP/multiOTPCredentialProvider#103]
I am using credentialProvider v5.9.6.1, it is working well for at least 3 months, but it didn't work anymore.
Here is the error message when I tried to test the multiotp:

> C:\Program Files\multiOTP>multiotp.exe username 123456
> PHP Warning:  'C:\Windows\SYSTEM32\VCRUNTIME140.dll' 14.0 is not compatible with this PHP build linked with 14.29 in Unknown on line 0 

I have to reinstall or repair the MS VC++, then it works.

I think other users have the same issue, does anyone know what is the cause of this issue ?
I understand that this is not a bug of this program, it is related to the environment of current PC, but I am really curious to know the casue and how to avoid this issue.

Thank you!

**Comment by multiOTP** [comment]
It seems that one of your program have installed an old MSVC 14.x runtime on your computer.
Regards,
