### ISSUE TITLE
Unresolved external symbols errors

### ISSUE THREAD

**Issue by alisolutions** [multiOTP/multiOTPCredentialProvider#11]
I am getting unresolved external symbols errors, following is the screen shot. 
I am running it on 'Debug' & 'Win32' Configuration, Visual Studio 2015 & Windows 10.

<img width="979" alt="screen shot 2018-04-26 at 11 06 02 am" src="https://user-images.githubusercontent.com/2880208/39288621-248428dc-4942-11e8-841e-949ceb98f2d2.png">

**Comment by alisolutions** [comment]
Build code in Release mode. Everything will work.
I become able compile it in debug mode as well after adding netapi32.lib and some other changes ...
But the dll created in the debug mode does not work properly, it gives strange behavior on LogonUI. Can anybody explain why debug mode generated dll shows unexpected behavior?

**Comment by multiOTP** [comment]
Hello,
can you please describe the strange behavior ?
Have a nice day

**Comment by multiOTP** [comment]
Hello,
A new rewrited edition will be available later this month.
Regards,
