### ISSUE TITLE
Tile image is not being visible on Logon UI.

### ISSUE THREAD

**Issue by alisolutions** [multiOTP/multiOTPCredentialProvider#12]
I have saved the image in C:\multiotp directory. But it's not being visible. Can anybody please help.

One more question, can you please guide me how I can show an icon in some corner of the screen. Like in the following image. Can anybody please give me even a clue, that how we can achieve that.

<img width="779" alt="screen shot 2018-05-03 at 7 28 55 pm" src="https://user-images.githubusercontent.com/2880208/39582902-5de002b0-4f08-11e8-8998-caa563fa7b59.png">

**Comment by DutchCloud4Work** [comment]
Hi Alisolutions,

As far as I know you cannot change that screen in Server 2012R2, You can do it in Server 2016.
In Server 2012R2 you can change the lock screen wallpaper.

**Comment by multiOTP** [comment]
Thanks DutchCloud4Work for sharing the information.

**Comment by mactruitasse** [comment]
Hello,

I update this closed issue by asking if it is possible to modify or to cancel the login screen of multiotp.

Regards

**Comment by multiOTP** [comment]
Hello,
If you want to "cancel" the multiOTP login screen, you have to uninstall it.
If you want to modify the logo, please check the Readme file.
Regards,
