### ISSUE TITLE
Resolve Hostname to IP

### ISSUE THREAD

**Issue by alisolutions** [multiOTP/multiOTPCredentialProvider#14]
Is their any way to add Hostname to ip lookup entry as a settings in NEPacketTunnelProvider? Because iOS does not allow to edit host name without jailbreaking. Can anybody please help me to provide any solution?
Thanks.

**Comment by multiOTP** [comment]
Hello,
are you sure your question is related to multiOTPCredentialProvider ? The credential provider is only working with Windows.
Have a nice day

**Comment by alisolutions** [comment]
Ohhh I apologize, that is a mistake. Please delete this issue.
