### ISSUE TITLE
-cp -debug "user01" ""12121  <- wrong question.

### ISSUE THREAD

**Issue by dhpark21** [multiOTP/multiOTPCredentialProvider#17]
ver 5.4.1.6 debug mode has wrong otp_pin, out "" pin
check it.
Thanks

20190403 0843430950: Reading REGISTRY Key:CLSID\{FCEFDFAB-B0A1-4C4D-8B2B-4FF4E0A3D978}\multiOTPPrefixPass
20190403 0843430950: multiotp_request
20190403 0843430950: cmd len: 12
20190403 0843430950: command len:27
20190403 0843430950: -cp -debug "user01" ""12121
20190403 0843430950: Reading REGISTRY Key: CLSID\{FCEFDFAB-B0A1-4C4D-8B2B-4FF4E0A3D978}\multiOTPPath
20190403 0843430950: Len 66
20190403 0843430950: Reading REGISTRY Key:CLSID\{FCEFDFAB-B0A1-4C4D-8B2B-4FF4E0A3D978}\multiOTPTimeout
20190403 0843430950: Reading REGISTRY Key:CLSID\{FCEFDFAB-B0A1-4C4D-8B2B-4FF4E0A3D978}\multiOTPServerTimeout
20190403 0843430950: Reading REGISTRY Key:CLSID\{FCEFDFAB-B0A1-4C4D-8B2B-4FF4E0A3D978}\multiOTPCacheEnabled
20190403 0843430950: Reading REGISTRY Key: CLSID\{FCEFDFAB-B0A1-4C4D-8B2B-4FF4E0A3D978}\multiOTPServers
20190403 0843430950: Len 2
20190403 0843430950: Reading REGISTRY Key: CLSID\{FCEFDFAB-B0A1-4C4D-8B2B-4FF4E0A3D978}\multiOTPSharedSecret
20190403 0843430950: Len 2
20190403 0843430950: Calling "C:\Program Files (x86)\multiOTP\multiotp.exe" -server-timeout=5 -server-cache-level=1 -cp -debug "user01" ""12121
20190403 0843430950: with options -server-timeout=5 -server-cache-level=1 -cp -debug "user01" ""12121
20190403 0843440528: WaitForSingleObject result: 0
20190403 0843440528: multiotp.exe Exit Code: 0
20190403 0843440575: 0 ??
20190403 0843440591: MultiotpCredential::failure text
20190403 0843440591: ERROR : Authentication failed (and other possible unknown errors)
20190403 0843440591: MultiotpCredential::Display Back link
20190403 0843440622: MultiotpCredential::SetStringValue, fieldID: 8
20190403 0843440638: Reading REGISTRY Key: SYSTEM\CurrentControlSet\Services\Tcpip\Parameters\Domain
20190403 0843440638: Len 2
20190403 0843440638: Reading REGISTRY Key: SYSTEM\CurrentControlSet\Services\Tcpip\Parameters\Hostname
20190403 0843440638: Len 32
20190403 0843560669: MultiotpCredential::UnAdvise
20190403 0843560669: MultiotpCredential::UnAdvise EventsV2
20190403 0843560669: MultiotpProvider::UnAdvise
20190403 0843560684: MultiotpProvider::_ReleaseEnumeratedCredentials
20190403 0843560684: ========== MultiotpProvider destroyed ==========

**Comment by multiOTP** [comment]
Thanks for the feedback, we will correct it in the next release.
Regards,

**Comment by multiOTP** [comment]
The next release will be available mid-May 2019.
Regards,

**Comment by multiOTP** [comment]
Release 5.6.1.5 contains this fix
