### ISSUE TITLE
ERROR: authentication failed on entering otp in logon UI

### ISSUE THREAD

**Issue by anekix** [multiOTP/multiOTPCredentialProvider#19]
I have succesfully install multiotp server on a windows box. and installed credential provider on another windows box(client). during setup of credential provider i was asked to validate the user, Verification was successful & Credential provider is visible on LongonUI

When i enter the otp & password i get Error : Authentication failed (and other possible unk nown errors). what could be the reason for this? how can i debug the issue?
my box with multiotp server is aslo reachable from other boxes.

**Comment by multiOTP** [comment]
Hello,
What version (opensource, pro, enterprise) of multiOTP are you using ?
Which build (version number) of multiOTP are you using ?

When you try log-in, is the network available on the computer ?
Do you have any log in multiOTP ?

**Comment by anekix** [comment]
@multiOTP i am using opensource version of multiOTP.
i am using `multiotp_5.4.1.6.zip` from https://download.multiotp.net/.

Yes the network is available when i log in.
is there any other place where i need to see log? i was looking at nginx log but i wasn't getting any when i was logging in.

also is there any specific way to debug the credential provider calls?

**Comment by anekix** [comment]
Looking into the source for multiOtp windows credential provider i found( in `MultiotpHelpers.h`):
```
#if _DEBUG
	#define DEVELOP_MODE TRUE
	#define SKIP_OTP_CHECK FALSE // Available in development only, ignore the OTP code check
	#define LOGFILE_NAME "C:\\multiotp-credential-provider.log"
```

I think these settings should allow myself to allow debugging.just wondering how is `if _DEBUG` value set to true ? Visual studio compiling in debug mode?

**Comment by multiOTP** [comment]
In multiOTP, in order to enable the debug mode permanently , you can run this command: 
multiotp -config debug=1

It should create a log folder with log file in it.

If you want to have the debug in the CP then you need to compile it in DEBUG mode

**Comment by anekix** [comment]
will building the CP also automatically register it? i am asking because i installed a fresh windows vm to build the CP after it was built i tried to restart and it asked for otp

**Comment by anekix** [comment]
so , in order to find out what was raising the exception i tried to launch a shell using `psexec -dsx cmd.exe` so that i could attach  a debugger to the `logoui.exe` process but the crash/start loop is too fast to attach the debugger.

**Comment by anekix** [comment]
it turns out that i just entered multiOTPLoginTitle in reg & it worked this time. but i am getting another error. i will close this issue for now & open a new one with relevant information,

cheers :)
