### ISSUE TITLE
Mass Deployment

### ISSUE THREAD

**Issue by Jonathan-Garber** [multiOTP/multiOTPCredentialProvider#2]
Since this installer doesn't support silent installs, any advice on a method of mass deployment?

**Comment by Jonathan-Garber** [comment]
Created my own solution. Closing issue.

**Comment by multiOTP** [comment]
Hello, are you using the WiX Toolset ? Do you plan to share it on GitHub ?
Thanks for your feedback.

**Comment by Jonathan-Garber** [comment]
My first few tests and currently working solution is a simple startup script pushed via GPO to selected computers in the domain. This way on boot OTP usage is enforced for the selected computers. Safe mode is still the only exception in our tests.

The installer script and uninstall script works very well so far. However it is customized to our environment. If I get time to clean it up and make it more user friendly/flexible I could post a gist of it.

**Comment by qzem** [comment]
@Jonathan-Garber 

Could you please share some general instructions how you've made this possible?
