### ISSUE TITLE
Customized credential provider not being loaded on machine other than on which it is being developed

### ISSUE THREAD

**Issue by anekix** [multiOTP/multiOTPCredentialProvider#21]
**multiOTPCredentialProvider**: V 5.4.1.6 based, with some custom changes
**Visula Studio Version**: VS2019
**Windows Version**: Win 10 may 2019 (x64)
**VS build configuration** : release

Hi, i have successfully built the credential provider (release version x64) on my development machine & **_it works fine_**. When i install it  on another machine (by just copying & pasting the dll file inside system32 folder as i am compiling it with _SKIP_OTP_CHECK_ for now ) the credential provider is not visible on the logon UI. What could be the reason for this ?
All registry entries are set properly.( can verify this as same entries works on development machine)

**Comment by multiOTP** [comment]
Hello,
on the computer, make sure you have installed the last Visual C++ runtime redistribution package from Microsoft for vc 2017.
https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads
Regards

**Comment by anekix** [comment]
I had built the solution using VS2019 & i had already installed the Visual C++ runtime from the link you mentioned but i cant figure out why the cp is not being loaded. any way to debug this further?

**Comment by multiOTP** [comment]
What is the computer OS ?

**Comment by anekix** [comment]
Windows 10 pro x64.

**Comment by multiOTP** [comment]
Copying the DLL is not enough, you have to register it !

**Comment by multiOTP** [comment]
[Registry]
Root: "HKLM"; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\Authentication\Credential Providers\{{FCEFDFAB-B0A1-4C4D-8B2B-4FF4E0A3D978}"; ValueType: string; ValueData: "multiOTPCredentialProvider"; Flags: uninsdeletekey
Root: "HKLM"; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\Authentication\Credential Provider Filters\{{FCEFDFAB-B0A1-4C4D-8B2B-4FF4E0A3D978}"; ValueType: string; ValueData: "multiOTPCredentialProvider"; Flags: uninsdeletekey
Root: "HKCR"; Subkey: "CLSID\{{FCEFDFAB-B0A1-4C4D-8B2B-4FF4E0A3D978}\InprocServer32"; ValueType: string; ValueData: "multiOTPCredentialProvider.dll"; Flags: uninsdeletekey
Root: "HKCR"; Subkey: "CLSID\{{FCEFDFAB-B0A1-4C4D-8B2B-4FF4E0A3D978}\InprocServer32"; ValueType: string; ValueName: "ThreadingModel"; ValueData: "Apartment"; Flags: uninsdeletekey
Root: "HKCR"; Subkey: "CLSID\{{FCEFDFAB-B0A1-4C4D-8B2B-4FF4E0A3D978}"; ValueType: string; ValueData: "multiOTPCredentialProvider"; Flags: uninsdeletekey
Root: "HKCR"; Subkey: "CLSID\{{FCEFDFAB-B0A1-4C4D-8B2B-4FF4E0A3D978}"; ValueType: string; ValueName: "multiOTPPath"; ValueData: "{app}\"; Flags: uninsdeletekey

**Comment by anekix** [comment]
i have registered using the reg file( so it works on development machine) but when i copy it to target & run the reg file again it should work as expected but its not working

**Comment by multiOTP** [comment]
DId you made some changes in the source ?

**Comment by anekix** [comment]
> DId you made some changes in the source ?

yes added a dropdown .but i made sure its working as i verified it on my development machine. is there anything else to be done after modifying the source?

**Comment by multiOTP** [comment]
Please compile the 5.4.1.6 edition without any change (except the SKIP_OTP_CHECK) and see if it works on the second machine, and keep us in touch,

**Comment by anekix** [comment]
i have tested it on 2 different machines( both development machine & it works on both with my changes) but as soon as i put it on another machine( normal user) its not loaded. i will check as you suggested to build 5.4.1.6. just wondering could it be any configuration related to release setting in visual studio?

**Comment by multiOTP** [comment]
As we have no idea about the changes you have made, we are sorry but we cannot help you more yet.

**Comment by multiOTP** [comment]
No news, we will clsoe the case.
If help still needed, please do a fork on GitHub, change and publish the modified source code, and open a new issue.
Regards,
Andre
