### ISSUE TITLE
Silent remote install

### ISSUE THREAD

**Issue by qzem** [multiOTP/multiOTPCredentialProvider#23]
Hi!

Are there any news about the msi installer. I've found an issue from 2018 where it was mentioned that installer will be available soon. If you don't have a msi installer ready, is there any other way to install MultiOTp Client Provider from command line, so I could push it with some tool? I've tried copying complete folder multiOTP from one computer where I have installed it manually and I have also copied multiotpClientProvider.dll from system 32, and I have imported registry files. Everything goes trough but client provider doesn't start. I can still logon with password only, there is no OTP field on login screen.

Thank you in advance.

Kind regards,

Q

**Comment by multiOTP** [comment]
Hello, the exe installer is written in this way to be sure that if somebody is installing the Credential Provider, a functional test is done before installing the Credential Provider.
For silent install, an MSI will be available soon (Q1-2020)
Regards,

**Comment by qzem** [comment]
Thank you for explaining. I am just wondering if there is maybe workaround for this until the msi is available?

**Comment by multiOTP** [comment]
Hello Q,

[Workaround is available here](http://www.1-2-3-4-5-6.net/cdn/multiOTPCredentialProvider/) (/silent and /verysilent supported)

Thanks in advance for your feedback !

Regards,

A.

**Comment by qzem** [comment]
Thank you very much. It is working great. I have only on minor complaint. When I try to login as other user, the domain is not recognized automatically so I have to enter username like this "domain\username". Is it possible to setup something in the registry so that domain would be recognized?

**Comment by multiOTP** [comment]
Already done in [release 5.6.1.5](https://github.com/multiOTP/multiOTPCredentialProvider/releases/tag/5.6.1.5) : ENH: Optional manual default computer/domain setup

As described in the readme, the registry entry is **multiOTPDefaultPrefix** : [Default computer/domain, default is '']. multiOTP use automatically the domain name as default, or computer name if the computer is not in a domain. You can set here a manual default computer/domain, like for example '.'

**Comment by multiOTP** [comment]
Does it work for you ? If yes, please close the ticket.
Regards,

**Comment by qzem** [comment]
It is working. Thank You.
