### ISSUE TITLE
Is the CredentialProvider have to the Windows password?

### ISSUE THREAD

**Issue by trac3me** [multiOTP/multiOTPCredentialProvider#25]
Hello there, great product:
       I am using CredentialProvider to  develop my custom login method，After my research，the CredentialProvider seems to require the user's original Windows password.  my question is : Is the CredentialProvider have to know the  original Windows password, and pass it to the operating system for verification, Otherwise user cannot log in successfully?

**Comment by trac3me** [comment]
Is the CredentialProvider have to use the Windows password?

**Comment by multiOTP** [comment]
Hello,
In any case, the CredentialProvider will always need that the user type the original Windows password in order to log into the computer in order to do the Kerberos authentication process in order to access the Windows ressources.
Regards,
