### ISSUE TITLE
Should there be more version?

### ISSUE THREAD

**Issue by lierbai** [multiOTP/multiOTPCredentialProvider#26]
When it leaves PHP and others,and give more choices. 
For example: 
1.strong double factor. 
2.Choose one of the two factors. 
3.Log mail can be configured and generated.
4. ...
it's going to be a great customer facing software.Even if it's free.
Sorry for the poor English.This is what I thought after I found it.

**Comment by multiOTP** [comment]
Hello,
multiOTP Credential Provider is a  free solution based on the multiOTP open source library, it will remain PHP based for the double factor authentication check.
You should look for a Radius Credential Provider implementation, it could fit your needs.
Regards,
