### ISSUE TITLE
Feature request : Command-line installation, with included parameters

### ISSUE THREAD

**Issue by leovictorsr** [multiOTP/multiOTPCredentialProvider#27]
Hello there!

Is there a way to install via command-line? I want to use this solution in remote terminals using telnet, and having the option to install via cmd/powershell would be really useful.
If there's not an option right now, which steps should I take with the project to build and have it installed locally by command line?

Many thanks.

**Comment by multiOTP** [comment]
Hi Leo,
Starting with version 5.6.2.x (published at the end of April), you will be able to install multiOTP using the "/VERYSILENT" option.
Until now, we have blocked the silent installation to avoid that the computer is no more accessible if the registry entries are not correct and the authentication process has not be tested at least once direct installation.
Regards,
Andre

**Comment by leovictorsr** [comment]
That's nice to know!
Is there a chance we will be able to set parameters so the installation is customized?
Right now I just need local installation so I want it to have no multiOTP server filled, for example.

Many thanks Andre,
Leonardo Rodrigues.

**Comment by multiOTP** [comment]
Hello,
Parameters customization will be available in the MSI version of the installer, planned for the end of the year.
Regards,

**Comment by multiOTP** [comment]
Hello,
the new version has been pblished. It's a MSI file you can then pass parameter as command line or use a transform file.
Best regards.
