### ISSUE TITLE
Sensitive data available to any user

### ISSUE THREAD

**Issue by tedkuban** [multiOTP/multiOTPCredentialProvider#28]
The registry key [HKEY_CLASSES_ROOT\CLSID\{FCEFDFAB-B0A1-4C4D-8B2B-4FF4E0A3D978}]
contains "multiOTPSharedSecret" and other sensitive data, with its security descriptor inherited from the parent key and allowing any user to read this data.

**Comment by mchubby** [comment]
What are the consequences for a leaked shared secret?
Can a hostile party use that to
- MITM the HTTP/self-signed HTTPS communication
- impersonate multiotp server or connector
- capture credentials (Radius?)
remotely or locally?

Or just intercept username and OTP ephemeral code ?

**Comment by soleroitsolutionsltd** [comment]
These are interesting question but it seems the projects is no anymore active :(

**Comment by multiOTP** [comment]
Hello,
The shared secret is only used to communicate between the local multiOTP and the network multiOTP.
Having this shared secret will allow a user to communicate with network multiOTP
During the Credential provider setup, you need to give the url of your multiOTP server and if you enter a https address as suggested then communications are encrypted between the multiOTP client and server.

Sensitive information are only sent back to the client if:
   authentication is successfull
   cache support was activated during Credential Provider setup
   cache is authorized on the server

Hope this helps.

Have a good day.

**Comment by multiOTP** [comment]
Last version of the installer is available here : https://download.multiotp.net/credential-provider/
Registry entry is not readable anymore by standard users.
