### ISSUE TITLE
FIXED: Issues upgrading Credential Provider from v5.0 to v5.6 not prompting for OTP

### ISSUE THREAD

**Issue by numericOverflow** [multiOTP/multiOTPCredentialProvider#29]
When upgrading from credential provider v5.0 to 5.6 I had issues getting OTP working.  The validation tests on the last steps of install wizard worked and said the CP was installed and validated pass/OTP, but when I actually tried to log in, I only got the generic password login screen and no OTP prompt.

I had to manually remove the old credential provider (v5.0.x from the registry in order to get the new one (v5.6.x) to work properly.    

- Delete this old key:
- Seems to cause problems and windows only used the generic password provider and not MOTP CP
> HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Authentication\Credential Provider Filters\{FCEFDFAB-B0A1-4C4D-8B2B-4FF4E0A3D978}

- This is the new key that gets installed, (i.e. KEEP this one):
> HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Authentication\Credential Provider Filters\{FCEFDFAB-B0A1-4C4D-8B2B-4FF4E0A3D978}

Maybe this info can be put in an FAQ or troubleshooting page so others can avoid spending a couple hours trying to fix.

**Comment by multiOTP** [comment]
Hello,
The first published version of multiOTP Credential Provider was 5.0.4.6, and the key was already 6F6F92D6-2D9C-46AD-8F4C-DAF92113B192. Any previous releases were not published by multiOTP.
Regards
