### ISSUE TITLE
Virus software causes problems

### ISSUE THREAD

**Issue by 7845258** [multiOTP/multiOTPCredentialProvider#3]
Hi,

We have the following environment:

**multiotp server virtual:**

This image here: http://www.1-2-3-4-5-6.net/cdn/multiOTP/hyper-v/multiOTP-open-source-Hyper-V-5.0.2.6.zip
The machine is running so far.

**client:**

OS on the client:
Windows 10 64-bit Version 1709 (build 16299.248)

Virus software on the client:
OfficeScan XG (Trend Micro) Agent Version: 12.0.4406 Service Pack 1

**Project:**

The multiOTPCredentialProvider should be installed on the Windows 10 clients.

**Problem:**
 
Installation of the multiOTPCredentialProvider:

with running virus scanner software, the multiOTPCredentialProvider version 5.1.0.4, 5.1.0.3
and version 5.0.4.8 are not installed, other versions we have not tested.

The system hangs up.

If the virus scanner software is deactivated, the multiOTPCredentialProvider can be installed without any problems.

Operation of the multiOTPCredentialProvider:

With the virus scanner software running, the additional login field for multiOTP will be displayed but
when logging in, the following text will be displayed: "Incorrect multiOTP OTP code"

If the virus scanner software is disabled, the login will ring perfectly.

An exception in the virus software we have already tried, but without success.

**Comment by multiOTP** [comment]
To avoid virus false positive alert, multiOTP.exe is NO more packaged in one single file using  Enigma, a php folder is now included in the multiOTP folder.

**Comment by multiOTP** [comment]
Please note also that the precompiled multiOTP.exe is digitally signed by our company, **SysCo systemes de communication sa**.
