### ISSUE TITLE
mode rdp

### ISSUE THREAD

**Issue by cez40** [multiOTP/multiOTPCredentialProvider#30]
To connect to a standalone server, you must declare   ".\<user>" or "<alea>\<username>" ("username" alone does not work)

Can you modify your code to avoid having to enter ".\" or "<alea>\user  in front of the name of the username to connect

thank you

**Comment by jbacksch** [comment]
I can confirm this issue in a local ony strong authentication installation.

**Comment by multiOTP** [comment]
Hello,
you can set the default logon prefix during the setup (which will set the multiOTPDefaultPrefix entry in the multiOTPCredentialProvider registry key)

Best regards.
