### ISSUE TITLE
Access to user configs only for administrators by default

### ISSUE THREAD

**Issue by jbacksch** [multiOTP/multiOTPCredentialProvider#33]
Only administrators should have access to the user configs in the directory C:\Program Files (x86)\multiOTP\users\ by default when using a local ony strong authentication installation.

**Comment by multiOTP** [comment]
Hello,
Thanks for your feedback. Even if the local data are encrypted, you're right, a stronger protection of this folder could be done automatically during the installation.
The rights on the multiOTP folder and it's sub-directories will be changed by the setup program in the next minor upgrade.
Regards,
Andre

**Comment by multiOTP** [comment]
The last available release fix this issue.

**Comment by multiOTP** [comment]
Hello,
this is done in the latest version of the credential provider msi installer.
Please give it a try.

Best regards
