### ISSUE TITLE
Instrution: How to Uprade a local ony strong authentication installation?

### ISSUE THREAD

**Issue by jbacksch** [multiOTP/multiOTPCredentialProvider#34]
From my point of view there is a instruction missing "How to Uprade a local ony strong authentication installation". 

e.g.

- Which files have to backed up?
- Do we have to reinstall over the new version of the multiOTPCredentialProvider only, or must the multiOTPCredentialProvider be deinstalled before.

**Comment by multiOTP** [comment]
Hello,
you only need to run the setup.
Best regards.
