### ISSUE TITLE
Entering password twice in multiotp

### ISSUE THREAD

**Issue by Anirudh-MV** [multiOTP/multiOTPCredentialProvider#35]
When I connect as a remote user through Remote Desktop, I have to type the password twice. But looking at the source code, multiotp implements UpdateRemoteCredentials function and has code within it. 

So multiotp shouldn't ask for password once again when I log in, but it does.

Am I missing something here?

**Comment by multiOTP** [comment]
Hello,
We are currently merging our solution into another open source Credential Provider. We should have the new solutions available in a few weeks.
Regards,
Andre

**Comment by multiOTP** [comment]
Hello,
This issue is fixed in the new multiOTP Credential Provider 6.x, currently in alpha tests.
Regards

**Comment by pearj** [comment]
@multiOTP where do I find the code for “ multiOTP Credential Provider 6.x”? Thanks

**Comment by multiOTP** [comment]
> @multiOTP where do I find the code for “multiOTP Credential Provider 6.x”? Thanks

Hello Joel,
Source code will be published here, as usual, as soon as we have a fully working version. We are now in beta tests.

**Comment by muqiuq** [comment]
Would be a very cool features / bugfix. Can't wait for beta tests to finish

**Comment by multiOTP** [comment]
Hello, we published the version 5.8.2.9
It handles authentication in two steps. First username and password, and then on a second screen OTP. No need to enter password twice anymore.
Best regards.
