### ISSUE TITLE
Questions local setup

### ISSUE THREAD

**Issue by jonathanmmm** [multiOTP/multiOTPCredentialProvider#36]
Hi,

I am using it in local mode.

The current setup takes a long time to login, I changed
ldap_time_limit=0 to zero
server_timeout=0 to zero but changed back to 5 after restart (as far as I know)
I entered no ip and in setting.
Even locking screen and entering again takes time, more than it took before, dont use any domain or so.
I entered no domain in installation, it showed PC-Name\UserName in the Test, I used the cmd command to add user.
First I used PC-Name\UserName, but couldn't use this to generate a qr code so I just used UserName without PC-Name\.
Now I have in the user folder both entries.
Test worked in the installation after I got the qr code for only UserName.

Also is it possible to use fingerprint + OTP instead of password + OTP?

Also does anonymous_stat=0 mean if set to 1 that stats are collected and send to you or are they just locally?

**Comment by multiOTP** [comment]
Hello,
Currently, fingerprint use is not possible.
anonymous_stat=1 will send anonymous statistics data through the Internet
anonymous_stat=0 will disable any statistics collection
Regards,
