### ISSUE TITLE
How to package multiOTPCredentialProvider.exe file? 

### ISSUE THREAD

**Issue by jefflks** [multiOTP/multiOTPCredentialProvider#39]
Hi MultiOTP,

I wish to learn on how to compile exe file based on source code. When I run build in Visual Studio 2019, there is only MultiotpCredentialProvider.dll is compiled. 

Thanks for guidance

**Comment by multiOTP** [comment]
Hi Jeff,
MultiotpCredentialProvider.dll is the only DLL created by the source code of this project.
If you want to create multiotp.exe, which is a stub to run multiotp.cli.php using PHP, you must have a look to the project https://github.com/multiOTP/multiotp and compile the launcher:
Regards,
Andre
