### ISSUE TITLE
In version 5.8.2.9, it is required to specify the multiOTP server

### ISSUE THREAD

**Issue by sashaqwert** [multiOTP/multiOTPCredentialProvider#42]
Good day!
Today I installed the latest version from GitHub (5.8.1.1) for testing in a virtual machine. I noticed a "bug" with the need to enter the password 2 times #35 .
After that I read README.md carefully and found that this problem was solved in version 5.8.2.9. This version is not on GitHub under Releases.

Can you please tell me if there are plans to add this version to Releases, or the only way now is to compile from source codes ...

Thank you!

**Comment by sashaqwert** [comment]
I found this version on the site:
https://download.multiotp.net/credential-provider/
https://download.multiotp.net/credential-provider/multiOTPCredentialProvider-5.8.2.9.zip

It is much more convenient to download files from GitHub than to search for links in solid, monotonous text.
Please add this version on GitHub under the Releases section.

**Comment by multiOTP** [comment]
Hello,
thanks for your feedback. We made the server mandatory on purpose. In which case does it make sense to leave the server field empty ?

Best regards

**Comment by sashaqwert** [comment]
Good day!
> In which case does it make sense to leave the server field empty ?

I left the server field blank as I have exactly 1 PC with RDP access.
To add users to the database and generate QR codes, I used the `multiotp.exe` command line arguments.
After adding users, I ran the installer again to pass the verification of the correct OTP settings.

**Comment by sashaqwert** [comment]
Good day!
I tested the new version.

I selected "/" as the server address (After installation, deleted the address from the config).
Added a user for [this](https://github.com/multiOTP/multiOTPCredentialProvider/wiki#local-only-strong-authentication-installation) instruction. Everything works without a server as in the previous version.

Thanks for making the installation easy! The installer no longer needs to be run 2 times!

**Comment by multiOTP** [comment]
Hi sashaqwert, not sure, it fix your issue, right ?

**Comment by sashaqwert** [comment]
Good day!

<details>
<summary>Now this works without server and AD domain</summary>

![изображение](https://user-images.githubusercontent.com/24974508/130578358-64dec6e1-8aeb-455a-9f35-37f285a92db5.png)

</details>

Thanks! Yes. It works for me now, but I don't know how much it will work.
The difference between working without a server is that the user database must be stored permanently, and not cached.

If there is no indication of the security in the installer, it is advisable to write a warning "You will need to configure manually via CMD".

**Comment by multiOTP** [comment]
Thanks for the hint, we will take care of your comment for the next version.
Regards,
