### ISSUE TITLE
Local Installation instruction incomplete

### ISSUE THREAD

**Issue by muqiuq** [multiOTP/multiOTPCredentialProvider#45]
For _local authentification_ only without server the URL of the multiOTP server had to be left empty. This is now no longer possible. 

Some more detailed instructions would be very helpful. Also the information if the saved SECRETS are lost or kept. 

See:
https://github.com/multiOTP/multiOTPCredentialProvider/commit/dfe7333df3896f367db3262a6acf518be173101a#r55465830

**Comment by devopsido** [comment]
localhost 

Seems to work too...

**Comment by multiOTP** [comment]
Hello,
we published a new version where the multiOTP server and secret key is not mandatory anymore.
Can you please try it ?
Best regards

**Comment by sashaqwert** [comment]
Good day @multiOTP !
Thanks! This works!

Tested on Windows 11 Enterprise multi-session (outside of Azure).
Do not ask me here, aboui ISOs...

<details>
<summary>Screenhshots</summary>

![изображение](https://user-images.githubusercontent.com/24974508/133429553-d67c039b-62da-4b88-a6a9-3284e32c97e7.png)
![изображение](https://user-images.githubusercontent.com/24974508/133429724-73ca7fce-a6ed-43a9-b4c6-e95952cb26f4.png)
![изображение](https://user-images.githubusercontent.com/24974508/133429896-df6f4cc3-132a-49b6-a0fb-2f567a312ec5.png)
![изображение](https://user-images.githubusercontent.com/24974508/133430111-9ca2e554-b581-4352-8924-ebecd3ec4291.png)
![изображение](https://user-images.githubusercontent.com/24974508/133430279-c646fab4-e05d-4128-8af0-e8deba052dc4.png)
![изображение](https://user-images.githubusercontent.com/24974508/133430372-b42d4919-02e8-4e0f-9794-4c0243d2fd6b.png)
![изображение](https://user-images.githubusercontent.com/24974508/133430528-a233aa85-b9ee-4749-8b3b-e9beabdc0af8.png)
![изображение](https://user-images.githubusercontent.com/24974508/133430825-b3675098-f635-40f5-8761-6d51712a4b95.png)


</details>

Unlike the previous version, the OTP entry screen now writes `user@PC-NAME`, which is much clearer than `user@WORKGROUP`.
