### ISSUE TITLE
 Invalid UPN

### ISSUE THREAD

**Issue by IGRYNS** [multiOTP/multiOTPCredentialProvider#46]
Good afternoon.

Made LDAP over UPN. Everything is successful on the server. Test OK.

On the client, when connecting to the server, the login is converted from tenant@ufw.local to tenant@ufw.local@testdomain.local.

Is there a solution to this problem? In May, they said that in a couple of weeks there will be an update and it will be fixed.

**Comment by multiOTP** [comment]
Hello,
Thanks for trying our Credential Provider. 
Can you please tell me where do you see : tenant@ufw.local@testdomain.local

We were able to reproduce the bug but we only saw it on the Windows login page. It looks good in multiOTP. Did you see it somewhere else ?

Can you please try to add the following **String** registry key :
HKEY_CLASSES_ROOT\CLSID\{FCEFDFAB-B0A1-4C4D-8B2B-4FF4E0A3D978}\hide_domainname
with value 1

Make sure you have an access without OTP to your server in case you need to remove this setting if it doesn't work. For example only activate OTP for RDP access.

Best regards

**Comment by IGRYNS** [comment]
tenant@ufw.local@testdomain.local is displayed in the Windows connection window and becomes the new login when connected to the system. The incoming UPN is changed.

MultiOTP is installed only for RDP mode.
I created the value you specified in the registry.

Synchronized samAccountName authorization succeeded.
Unfortunately, authorization by synchronized userPrincipalName is not available.

In general, changing this registry key did not help with UPN authorization.
Earlier, I managed to solve this problem of entering a login in the format: testdomain\tenant@ufw.local

Best regards

**Comment by IGRYNS** [comment]
Maybe the problem is hiding in the generation of the QR code?
The generated code is valid for the following account: tenant

The login is always formed in the userPrincipalName format.

**Comment by multiOTP** [comment]
Hello,
As written in the multiOTP readme, did you tried to syncrhonised your LDAP using the userPrincipalName instead of the saMAccountName ?
Set the user CN identifier (sAMAccountName, eventually userPrincipalName):
**multiotp -config ldap-cn-identifier="userPrincipalName"**

**Comment by IGRYNS** [comment]
Yes, I did everything with these settings.

**Comment by multiOTP** [comment]
This way, users synced from AD and created in multiOTP are now "tenant@ufw.local", and not just "tenant", right ?

**Comment by multiOTP** [comment]
What is displayed in the log file of multiotp after a refused log in ? Which username exactly ?

**Comment by IGRYNS** [comment]
Good afternoon.
There is a server with AD: testdomain.local
There is an alternative suffix: ufw.local

There are 2 users:
 1 - tenant1@testdomain.local
 2 - tenant2@ufw.local

Task: connecting to a server with MultiOTP authorization by userPrincipalName

There is a server with MiltiOTP server.
Synchronize with AD by userPrincipalName.
Users in MultiOTP
tenant1@tomtest.local [AD / LDAP]
tenant2@ufw.local [AD / LDAP]

Checking multiotp -display-log -log -debug "user" "token" on the client.
tenant1@tomtest.local - OK
tenant2@ufw.local - OK

Via RDP:
Login: tenant1@tomtest.local - OK - but login changed to tenant1@tomtest.local@tomtest.local
Login: tenant2@ufw.local - OK - but login changed to tenant2@ufw.local@tomtest.local

On the client, the hide_domain key was set to 1
Login: tenant1@tomtest.local - OK
Login: tenant2@ufw.local - OK

Perhaps there was a mistake in my setup. But thanks for the recommendation on hide_domain!

I noticed such a problem that for some reason on the client, for some reason I do not understand, the config server-secret is changing. We have to update it.
Perhaps after several unsuccessful attempts, it changes?
The logs indicated that server banned.

**Comment by multiOTP** [comment]
Hello,
You are talking about the testdomain.local wirh an alternative suffix ufw.local, and after you write tomtest.local.
Could you please clarify ?
Thanks

**Comment by IGRYNS** [comment]
yeah? sorry.
Main domain - testdomain.local
There are no more problems with authorization.

Now I'm checking how I can synchronize MultiOTP and Nextcloud.
The config server-secret problem has not yet been examined deeper.

**Comment by multiOTP** [comment]
Hello,
You're welcome.
The double domain issue was only a display issue, but it will be corrected in the next release.
Regards.
