### ISSUE TITLE
Offline UPN is not Working

### ISSUE THREAD

**Issue by Mahaboob-Aslam** [multiOTP/multiOTPCredentialProvider#47]
Hi 

Good Morning!

I trying to use MultiOTP CredentialProvider.

What I am seeing is "MultiOTP Credential Provider works fine, **when domain is online and domain is reachable, login with UPN works fine,  If I try to login when domain is not Online and domain is not reachable, UPN is not working"  i.e., Credential Provider does not allow me to login**.

I am following these steps:

Made the AD Server machine offline.
Entered my Credentials as follows in the fields:
UserName : username@domain.com
Password:  ***********
After pushing the  < SUBMIT> button, I am seeing the following message.

"_We cant sign you in with this credential because your domain isn't available.  Make sure your device is connected to your Organisation's network and try again. If you previously signed in on this device with another credential, you can sign in with that Credential._"

Could you Please help me out how to enable or what has to be done in the code to implement the "Offline UPN to work."
Please do the needful.

Regards
Aslam

**Comment by multiOTP** [comment]
Hello,
Thanks for trying our solution.
Did you successfully loged in using UPN and OTP on the same machine with AD online ?
Do you have a multiOTP server or do you use a local multiOTP ?
It looks like this error message is coming from Windows. Can you try the same process on the same machine but without multiOTP credential provider ?

Best regards

**Comment by multiOTP** [comment]
Hello,
After looking for some solutions, we decided to implement a UPN offline cache starting in the 5.8.9.x release, has UPN offline information cannot be available natively from Microsoft Windows.
Regards,

**Comment by multiOTP** [comment]
Hello,
Version 5.9.0.3 resolves the offline UPN issue.
Regards.
