### ISSUE TITLE
Installer transform / logo change not recognized

### ISSUE THREAD

**Issue by devopsido** [multiOTP/multiOTPCredentialProvider#49]
After installation of 5.8.2.9 on a standalone server (that had previously had 5.8.0.2 installed and working)

The transform seems to pickup the new logo and location (the setting from the transform appears in the correct location in the registry) under:

Computer\HKEY_CLASSES_ROOT\CLSID\{FCEFDFAB-B0A1-4C4D-8B2B-4FF4E0A3D978}  under v1_bitmap_path  

Other changes from the transform appear to work as expected, but the logo is never changed.

Note: This is great work. Thank you. I sort of miss the option to change the login BMP from the executable (now installer)

**Comment by khangcnttspkt** [comment]
> After installation of 5.8.2.9 on a standalone server (that had previously had 5.8.0.2 installed and working)
> 
> The transform seems to pickup the new logo and location (the setting from the transform appears in the correct location in the registry) under:
> 
> Computer\HKEY_CLASSES_ROOT\CLSID{FCEFDFAB-B0A1-4C4D-8B2B-4FF4E0A3D978} under v1_bitmap_path
> 
> Other changes from the transform appear to work as expected, but the logo is never changed.
> 
> Note: This is great work. Thank you. I sort of miss the option to change the login BMP from the executable (now installer)

Hi @devopsido ,

![image](https://user-images.githubusercontent.com/26158447/133017793-304f2454-ed31-41c2-a44d-e131ada935fd.png)

Can you check The properties is correct?

**Comment by devopsido** [comment]
Humm. It seems that my image that does not work has .1 K more data than the original 9which has 48k. Possibly some header info or something added by software. I have opend your image, pasted my image over it and saved it and it worked. Sorry for the alarm.

<img width="227" alt="image" src="https://user-images.githubusercontent.com/54953898/133137725-01f59b7d-865b-4bc7-a430-95d287d09ba6.png">
