### ISSUE TITLE
SMS anfordern

### ISSUE THREAD

**Issue by 7845258** [multiOTP/multiOTPCredentialProvider#5]
Hallo,

Wir möchten auf einer Website einen Button einbauen, um den SMS-Code anzufordern.

Gibt es dazu eine API oder Dokumentation?

Vielen Dank für die Info.

**Comment by multiOTP** [comment]
Hallo,

multiOTPCredentialProvider hat schon eine Button, um den SMS-Code anzufordern.
Aber Sie haben wahrscheinlich eine multiOTP Server (open source oder commercial) installiert, richtig ?

Verschiedene Möglichkeiten:
- multiOTP Server ist eine Radius Server, So können Sie eine Radius Anfrage machen (username : [username] und password : "sms"). Eine Radius PHP Library gibt es zum Beispiel hier : https://github.com/dapphp/radius
- multiOTP Server könnte auch als "CLI" gebraucht sein : /path/to/multiotp.php [username] sms
- multiOTP Server hat eine SOAP-Dienst, und dieser Dienst ist kompatibel mit OpenOTP, und Sie können eine openotpNormalLogin SOAP Anfrage machen (username : [username] und password : "sms")
- multiOTP Enterprise commercial Server hat eine Web API

Mit freundlichen Grüssen

**Comment by 7845258** [comment]
Hallo,

Das sind genau die Hinweise die wir brauchten.
Wir werden es jetzt via dem ersten Punkt (...eine Radius Anfrage machen...) lösen.

Vielen Dank.

**Comment by multiOTP** [comment]
You're welcome.
Mit freundlichen Grüssen aus der Schweiz
