### ISSUE TITLE
MultiOTP Credential Provider + Continent TLS 2.0

### ISSUE THREAD

**Issue by Uncert** [multiOTP/multiOTPCredentialProvider#51]
Hello everybody!
We have use MultiOTP + MultiOTP Credential Provider 5.8.4.0 and another system for providing secure remote access to
web applications using GOST encryption algorithms (https://www.securitycode.ru/download_center/?section=downloads&product=%D0%9A%D0%BE%D0%BD%D1%82%D0%B8%D0%BD%D0%B5%D0%BD%D1%82%20TLS) 

I noticed strange work with the installed provider. When I try to log in to sites using Continent TLS, I get a blank Windows snap-in for choosing a certificate.
When using provider version 5.8.1.1 - everything works fine. 

https://ibb.co/kBYr5Bg - image error

**Comment by Uncert** [comment]
Yes, of course, I will prepare and record a video of the process on a completely clean system.

**Comment by multiOTP** [comment]
Ok, thx.

**Comment by JoseLuisCaHu** [comment]
¿Have you found a solution? I have the same problem with Windows certificates dialog, it doesn't show password textbox nor Allow button when Multiotp Credential Provider is installed. I am using 5.8.5.1 version but it happens with 5.8.4.0 too.

![With MOTP Credential Provider installed](https://user-images.githubusercontent.com/98516321/151319133-bb05773e-a13a-4a69-b3d8-10eab81f688d.JPG)
![Without MOTP Credential Provider installed](https://user-images.githubusercontent.com/98516321/151319161-24ac37dc-36f5-4995-bea3-d683dd8c62f1.JPG)
.

**Comment by Uncert** [comment]
The solution has not yet been found, while we had a huge influx of work and I did not even have time to prepare a test bench ...

**Comment by JoseLuisCaHu** [comment]
I have found a temporary solution. It does not happen if you change the value of the "EnableLUA" registry key to 0 in "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System" or by disabling the entry "User Account Control: Run all administrators in Admin Approval Mode" in a GPO in "Computer Configuration -> Policies -> Security Settings -> Local Policies -> Security Options".

**Comment by multiOTP** [comment]
thanks for the temporary solution. As soon as we have access to Uncert test computer we will have a look at what is going on.
Best regards

**Comment by JoseLuisCaHu** [comment]
The issue still occurs with non-administrator users despite applying the temporary solution. I have found it happens because non-administrator users don't have read permissions on registry key HKEY_CLASSES_ROOT\CLSID\{FCEFDFAB-B0A1-4C4D-8B2B-4FF4E0A3D978}. It is solved by giving them read permission.

**Comment by multiOTP** [comment]
Thanks for the fix @JoseLuisCaHu. The fact that the user must have a read access to the registry key HKEY_CLASSES_ROOT\CLSID{FCEFDFAB-B0A1-4C4D-8B2B-4FF4E0A3D978} seems to be an issue only with Continent TLS 2.0. Therefore, we will not change the instalaltion process on our side.
Regards
