### ISSUE TITLE
Windows 11 installation error

### ISSUE THREAD

**Issue by AndreyCher** [multiOTP/multiOTPCredentialProvider#52]
When i am trying to install multiotp credentional provider, get error on installation step.  Error name "The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code  is  2892"

In event log this error decribed as: 
"Product: multiOTPCredentialProvider -- The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2892. The arguments are: multiOTPTimeoutCP, 0000003C, "

detailed information:
```
EventData 

Product: multiOTPCredentialProvider -- The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2892. The arguments are: multiOTPTimeoutCP, 0000003C,  
   (NULL) 
   (NULL) 
   (NULL) 
   (NULL) 
   (NULL) 
   7B35323637444330302D314542312D344246412D414133372D3346363935323635383539307D 
--------------------------------------------------------------------------------
Binary data:

In Words
0000: 3632357B 30434437 45312D30 342D3142 
0010: 2D414642 37334141 3646332D 36323539 
0020: 39353835 7D30   

In Bytes
0000: 7B 35 32 36 37 44 43 30   {5267DC0
0008: 30 2D 31 45 42 31 2D 34   0-1EB1-4
0010: 42 46 41 2D 41 41 33 37   BFA-AA37
0018: 2D 33 46 36 39 35 32 36   -3F69526
0020: 35 38 35 39 30 7D         58590}
```

I am undestand what in specification win11 not present. But looks like this error refers to installer problem. If it possible add win 11 to support of this program

**Comment by AndreyCher** [comment]
Sorry my mistake i was start install without admin rules, because it was not asked automatically, i was confused. Run msi in admin mode fixed this problem

**Comment by multiOTP** [comment]
Thanks for the feedback.
