### ISSUE TITLE
question 2fa password - Is it possible to not ask for 2FA during a specific timeout ? Is it possible to save the username ?

### ISSUE THREAD

**Issue by killmasta93** [multiOTP/multiOTPCredentialProvider#57]
Hi
I was wondering if the client 2fa could add a timeout or a way to not ask for the password every 10min or so?
For ex:
user logs in with password then computer locks it and the user puts in the 2fa, then the computer locks again but has not passed the 10min which the user only puts in the password which would not ask 2fa until it passed the 10mins

**Comment by killmasta93** [comment]
Hi @multiOTP  i was looking though the config of agent but didnt find any option nor did i found the option to allow to save the username so the user didnt have to reput the username everytime it locks it self

**Comment by multiOTP** [comment]
This is not implemented yet.

**Comment by multiOTP** [comment]
Since 5.9.1.0, last username is available. It's now also possible to ignore 2FA when computer is locked (option is not working when Fast User Switching is activated, that's why we ask now during installation if you want to disable or not the Fast User Switching)
Regards,

**Comment by killmasta93** [comment]
Thank you so much

**Comment by multiOTP** [comment]
Hello, sorry, last username will be available in 5.9.2.x, only ignoring 2FA when computer is locked has been released in 5.9.1.0).
regards,

**Comment by multiOTP** [comment]
It's now possible (5.9.2.1) to not ask for 2FA during a specific timeout (in minutes). This is only available for unlock process.
