### ISSUE TITLE
.reg file to unregister / "deactivate" the MultiOTP Crredential Provider may have the wrong GUID

### ISSUE THREAD

**Issue by devopsido** [multiOTP/multiOTPCredentialProvider#58]
The reg file multiOTPCredentialProvider-unregister.reg has a line to remove:

[-HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Authentication\Credential Provider Filters\{FCEFDFAB-B0A1-4C4D-8B2B-4FF4E0A3D978}]

...but after merging the reg file there is a remaining key at: 

[-HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Authentication\Credential Provider Filters\{FCEFDFAB-B0A1-4C4D-8B2B-4FF4E0A3D979}]

The path is different! (the last character is a 9 rather than an 8)

After merging the multiOTPCredentialProvider-unregister.reg file I was still being prompted for to login a second time -- but only for username and password (no OTP). 

After removing:

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Authentication\Credential Provider Filters\{FCEFDFAB-B0A1-4C4D-8B2B-4FF4E0A3D979}

I am no longer prompted to login a second time and everything works as expected.

**Comment by multiOTP** [comment]
Hello,
Thx for the feedback, the usual way to uninstall it is now to use the "regular" uninstaller, but we have fixed the .reg file also on the download website, and it will be integrated in the next ZIP file.
