### ISSUE TITLE
multiOTPCredentialProvider dropping the first letter of the username at lookup

### ISSUE THREAD

**Issue by devopsido** [multiOTP/multiOTPCredentialProvider#59]
After upgrading a "standalone" installation on a workgroup computer (from 5.8.2.9 to 5.8.8.0) we were consistently seeing the error for a wrong One-Time Password.

After increasing debug level and checking the logs, the user account being checkd by MultiOTP was missing the first character of the username. For example for a user who logged in with the name 'admin' we see a log entry for the user dmin:

2022-05-21 13:20:10	warning		System	Error: database file C:\PATH_TO\multiOTP\.\users\dmin.db for user dmin does not exist	0	SERVERNAME

If I copy the file admin.db and rename it dmin.db login proceeds as expected.

Unfortunately, rolling back to the old version has not resolved this issue. Any asistance would be appreciated!

**Comment by multiOTP** [comment]
Hello,
What did you do as a rollback exactly ? uninstall 5.8.2.9 and reinstall 5.8.8.0, or just replacing the DLL ?
Are you using a full local edition (No multiOTP server anwhere) ?
We are not able to reproduce the issue here.

**Comment by devopsido** [comment]
I just tried it replacing ONLY the 2 dll files and I see the same issue, but I am able to put the 5.8.2.9 dlls back and it works again.

I see sucessful logins before the switch in the log:

2022-05-22 16:32:06	notice	testuser	User	OK: User testuser successfully logged in (using Credential Provider) with YubicoOTP token	0	SERVERNAME

Then the failure after the switch:

2022-05-23 15:55:49	warning		System	Error: database file *PATH*\multiOTP\.\users\estuser.db for user estuser does not exist	0	SERVERNAME

Putting back the old dlls resolves and allows login again.

**Comment by multiOTP** [comment]
Please send us your email address to info@multiotp.net and we will send you a specific DLL to test.

**Comment by devopsido** [comment]
Done. Ready to test!

**Comment by multiOTP** [comment]
Version 5.9.0.3 is now available and resolve various issues, including this one.
