### ISSUE TITLE
Password change option when the password of the account is expired

### ISSUE THREAD

**Issue by multiOTP** [multiOTP/multiOTPCredentialProvider#6]
Hello,

I have this problem: at a time when the password of the account is expired, i can not change it because I can't log in to the account with expired password.
Is multiOTP Credential Provider support password change?

How can this be solved?

_(originally posted by  TarlanAbdullayev on 20 Dec. 2017)_

**Comment by multiOTP** [comment]
Hello,
Currently multiOTP credential provider doesn't support password change.
It's on the todo list.
Best regards

**Comment by multiOTP** [comment]
Hello,

Thanks for your answer.
And approximately when multiOTP credential provider with password change feature will be ready?

_(originally posted by TarlanAbdullayev on 12 Jan. 2018)_

**Comment by multiOTP** [comment]
It's expected for end of March 2018

**Comment by multiOTP** [comment]
Due to lack of time for open source projects, this modification is postponed (expected June/July 2018).
Regards,

**Comment by multiOTP** [comment]
Due to lack of time for open source projects, this modification is postponed (expected end of May 2019).
Regards,

**Comment by OttoChamo** [comment]
@multiOTP Hello, Did you finally add this feature or is it postponed again? I am having the same issue.

Regards.

**Comment by multiOTP** [comment]
Hello Otto,
We are currently in discussion with a donator in order to sponsor this feature.
Regards,

**Comment by OttoChamo** [comment]
@multiOTP How much are you asking for developing this feature and How long would it take to be done?

**Comment by multiOTP** [comment]
Hello Otto,
We have made an evaluation and sent it to your collegue Ender.
Regards,

**Comment by Mohitkiran** [comment]
Hi, is this feature implemented?

**Comment by multiOTP** [comment]
This feature is a sponsored development and will be available in a few weeks.
Regards

**Comment by Mohitkiran** [comment]
When can we expect this? Any rough estimate?

**Comment by multiOTP** [comment]
Should be there for Christmas :-)

**Comment by Mohitkiran** [comment]
Awesome thank you.

**Comment by OttoChamo** [comment]
So the official date for this feature is christmas?

**Comment by OttoChamo** [comment]
When can we give you the donation you asked for this feature?

**Comment by HenriqueSSantana** [comment]
Hello from Brazil.
This project still alive? Do you have any predictions about the implementation of the feature?
Tks!

**Comment by multiOTP** [comment]
Hello Henrique,
Yes, the feature will be available later this year.
Regards,

**Comment by khangcnttspkt** [comment]
HI MultiOTP,
This feature still alive?
Thank you!

**Comment by Amanallah-Focus** [comment]
Hello,
Any update regarding when this feature will be released ?
Best Regards,

**Comment by multiOTP** [comment]
Hello,
We are currently merging our solution into another open source Credential Provider. We should have the new solutions available in a few weeks.
Regards,
Andre

**Comment by multiOTP** [comment]
Hello,
This issue is fixed in the new multiOTP Credential Provider 6.x, currently in alpha tests.
Regards

**Comment by multiOTP** [comment]
Hello, the new Credential Provider has been published. It handles password change.
Best regards
