### ISSUE TITLE
Credential provider blocks browser from requesting FIDO2 auth

### ISSUE THREAD

**Issue by MBPotier** [multiOTP/multiOTPCredentialProvider#61]
Hello,

After installing multiOTP credential provider, web browsers are unable to request FIDO2 authentication. Here a screenshot what the FIDO2 auth popup looks like after multiOTP credential provider is installed:
<img width="513" alt="multiotp_installed" src="https://user-images.githubusercontent.com/90350656/171256415-32984105-27c3-41f4-949f-8188a7643280.PNG">
 Note that you are not prompted to touch your security key. Tapping the button on your security key anyways does not log you into the website and authentication fails. I tried various settings for MULTIOTP_CPUSLOGON, MULTIOTP_CPUSUNLOCK, and MULTIOTP_CPUSCREDUI in my mst including setting them all to 3d (the most permissive option), but FIDO2 auth still failed. Below is a screenshot of how the FIDO2 auth popup looks without multiOTP credential provider installed.
<img width="517" alt="no_multiotp" src="https://user-images.githubusercontent.com/90350656/171256746-0897b067-7d54-4b7a-b5bb-e46ba597f3bd.PNG">
When you tap the button on your security key, you are logged into the site.

Thanks.

**Comment by sashaqwert** [comment]
try https://github.com/multiOTP/multiOTPCredentialProvider/issues/51#issuecomment-1091635011

It seems to me that the screenshots are very similar to that problem.

**Comment by multiOTP** [comment]
This has been fixed in release 5.9.1.0
Please note also that the issue described in #28 is not a security issue, as the shared secret is only a symmetric key which was useful when the multiOTP open source server was not responding in SSL, but now the trafic is always done in SSL.
Regards,
