### ISSUE TITLE
Changing bitmap

### ISSUE THREAD

**Issue by cdyer5050** [multiOTP/multiOTPCredentialProvider#63]
Adding a custom bitmap and adding the path to the registry or during install with a transform file doesn't work.  The login logo never changes. I am using the latest version.

**Comment by multiOTP** [comment]
Hello, can you please send us a copy of the registry (HKEY_CLASSES_ROOT\CLSID{FCEFDFAB-B0A1-4C4D-8B2B-4FF4E0A3D978}) and a copy of the logo files you are trying to use ?

Best regards

**Comment by cdyer5050** [comment]
[bitmap&registry.zip](https://github.com/multiOTP/multiOTPCredentialProvider/files/9270638/bitmap.registry.zip)
Bitmap and registry are attached. I removed the server IP and shared secret for obvious reasons.

**Comment by multiOTP** [comment]
Hello,
looks like the file format is not supported. Don't know why. I just opened it in Microsoft Paint and saved it as bmp 24 bits and it works.
Can you please try it ?

Best regards

**Comment by multiOTP** [comment]
Hello,
Your BMP was compressed using **"Huffman 1D"**, and Windows need an **uncompressed** BMP.
Source : https://en.wikipedia.org/wiki/BMP_file_format
Offset 30 (1E in hexa), the compression byte was 3 (Huffman 1D) in your BMP file, and not 0 (uncompressed)
Regards,
