### ISSUE TITLE
How to modify the user profile in the window login interface

### ISSUE THREAD

**Issue by tc01435** [multiOTP/multiOTPCredentialProvider#73]
I want to modify the user profile of the login interface by modifying the registry, but it doesn't seem to work

**Comment by multiOTP** [comment]
Hello,
Are you talking about the login image displayed ?
You have to give the complete path and filename of a bitmap image. The image must be a version 3 Windows BMP file with a resolution of 128x128 pixels.
Regards,

**Comment by tc01435** [comment]
TKS!!!
