### ISSUE TITLE
Serious Problem : Account loss (by design : security measure if account is no more available in the AD/LDAP during successful sync)

### ISSUE THREAD

**Issue by tc01435** [multiOTP/multiOTPCredentialProvider#75]
Multiple tests revealed the following problem.
Computer only synchronize a specified AD account lisa can use WITHOUT2FA login, when I add a new AD account coco, coco.db file is available, but found that the previous lisa.db file under C:\Program Files (x86)\multiOTP\users sometimes disappeared, resulting in the original account lisa can not log into the computer anymore, WHY?
The script is added in the following way
cd C:\Program Files (x86)\multiOTP
multiotp -config ldap-users-dn="CN=coco,OU=TEST,DC=SC,DC=cn"
multiotp -ldap-users-sync

**Comment by multiOTP** [comment]
Hello,
Could you please write the message with english characters please ?
Regards

**Comment by tc01435** [comment]
How to install a "multiOTP open source" server on an other server

**Comment by tc01435** [comment]
Where are the installation packages and tutorials available

**Comment by multiOTP** [comment]
Hello,
The repository for the multiOTP open source server is here :
https://github.com/multiOTP/multiOTP
Regards,

**Comment by multiOTP** [comment]
Please not also that by default, if an account is **not existing anymore** during AD/LDAP sync **for at least 30 days**, multiOTP open source server will delete it during during sync process.

This option is explained in the readme of the multiOTP server:
```
 multiotp -sync-delete-retention-days=days of retention before deleting a no
                                      more existing AD/LDAP user
                                      (0=disable only the user, do not delete)
```

**Comment by multiOTP** [comment]
This is of course a security measure, if you sync AD/LDAP and the user doesn't exist in the AD/LDAP anymore, you don't want to give it access anymore. Please note alsop that you should schedule the AD/LDAP to something like at least every hour or every day. The commercial edition do the schedule automatically, but in the open source edition, you will have to schedule it yourself.
