### ISSUE TITLE
questions related to overall quality in the multiOTP credential provider

### ISSUE THREAD

**Issue by ashishsabu** [multiOTP/multiOTPCredentialProvider#77]
Hello Team, 
I have doubts regarding below points. Could you please assist.

Below questions are related to overall quality in the multiOTP credential provider.
 
a. Are their guidelines available for contributors?
b. Is there a guideline available for the review process ?
c. Are there guidelines available for the review and check-in process ?
d. Are there clear roles and responsibilities in the community ?
e. Are  there any rules for secure development ?

Thanks and Regards,
Ashish Sabu

**Comment by multiOTP** [comment]
Hello Ashish,
No, we don't have any guideline yet for contributors. The project is entirely backed by our core team.
Regards
