### ISSUE TITLE
How to take build and proper steps to install in win server 2016

### ISSUE THREAD

**Issue by lokeshsuhas** [multiOTP/multiOTPCredentialProvider#8]
Hi Team,

I am writing a build installer using Visual Studio 2017 to make an exe out of this multiotpcredential provider, but when i tried to make the dll vsdrfCOMSelfReg the installer fails to execute. I debugged futher with regsvr32 it returns as "dll was loaded but the entry point DLLRegisterServer was not found".

I even tried with wixsetup used in "https://github.com/LastSquirrelIT/MultiOneTimePassword-CredentialProvider" -> when i add reference to the built dll it throws dll doesnt have proper assembly manifest, i have debugged it by opening the dll in visual studio i could see the embedded manifest . No idea why its throwing.

i even referred the dll's available in stable folder, but still the same problem.

Can you please tell me the steps how to install the dll in win server 2016. Note: setting vsdrfCOM works, but when system is restarted nothing happens directly logs in.

Any tips or help is much appreciated.

**Comment by multiOTP** [comment]
Hello,
Please check the @multiOTPCredentialProvider.iss, which is the source file for the InnoSetup (http://www.jrsoftware.org/isinfo.php) we use to create the exe installation.
An unattended installation file (.msi) using WiX Toolset (http://wixtoolset.org/) will be available in a next version.
Regards,
