### ISSUE TITLE
 Does the community perform any security/penetration test on multiotp credential provider?

### ISSUE THREAD

**Issue by ashishsabu** [multiOTP/multiOTPCredentialProvider#80]
Hello Team,

Does the community perform any security/penetration test on multiotp credential provider?
Could you please assist.

Thanks and REgards,
Ashish Sabu

**Comment by multiOTP** [comment]
Hello Ashish,
We do internal testings of our project, but we don't have setup yet a community group to organize and perform any security/penetration tests.
Regards
