### ISSUE TITLE
"Normal", non admin users can access HKEY_CLASSES_ROOT\CLSID\{FCEFDFAB-B0A1-4C4D-8B2B-4FF4E0A3D978}

### ISSUE THREAD

**Issue by lisbkooklyn** [multiOTP/multiOTPCredentialProvider#81]
"Normal", non admin users can access HKEY_CLASSES_ROOT\CLSID\{FCEFDFAB-B0A1-4C4D-8B2B-4FF4E0A3D978} 
and look for "excluded_account" key. This reduce security of this project. Removing "users" group form access list fix problem and dose not  break anything.

**Comment by multiOTP** [comment]
Hello lisbkooklyn,
Read access to HKEY_CLASSES_ROOT\CLSID{FCEFDFAB-B0A1-4C4D-8B2B-4FF4E0A3D978} is needed for some features, like unlock process. "excluded_account" is a "legacy" key that can be superseeded easily by the "without2fa" feature.
If you want to exclude some accounts from 2FA without using "excluded_account", you can give this accounts a "without2fa" token, which will not ask for a 2FA, and this information will not available in the registry.
Regards,

**Comment by lisbkooklyn** [comment]
Thank you for quick reply. Amazing project. Donate some money and will ask other people who will use this project do the same.

**Comment by multiOTP** [comment]
Hello lisbkooklyn,
Thanks for your feedback and your donation.
Regards,
