### ISSUE TITLE
Sporadic issue with customized multiOTP login image

### ISSUE THREAD

**Issue by ashishsabu** [multiOTP/multiOTPCredentialProvider#82]
Hello Team,

I have created customized login image (of version 3 Windows BMP file with a resolution of 128x128 pixels)  and replace the existing loginLogo.bmp image.
I have also updated the path in v1_bitmap_path registry settings.
the above configuration works fine and I am able to see my customize image in login screen but sometime after 4-5 login attempts the login screen display the default multiOTP bitmap image.
Could you please suggest is there any settings I need to update ?

Thanks and Regards,
Ashish Sabu

**Comment by multiOTP** [comment]
Hello Ashish,
What is the full path of your customized bitmap ?
Could you send us also this bitmap (if it is a sensitive data, please send to "info - at - multiotp.net")
Regards,

**Comment by ashishsabu** [comment]
Hello Team,

Full path of customized bitmap image -   "C:\Program Files (x86)\multiOTP\loginLogo.bmp"
I have shared customized login bitmap to info - at - multiotp.net.
Could you please check and let me know if any modification is needed.

Thanks and Regards,
Ashish Sabu

**Comment by multiOTP** [comment]
Hello Ashish,

The logo you sent us is an resolution of 194x171 pixels !

Regards,

**Comment by ashishsabu** [comment]
Hello Team,

Please find the correct image.
by mistake I sent the wrong image.

thanks and Regards,
Ashish sabu

**Comment by multiOTP** [comment]
Hello Ashish,
We were not able to reproduce your issue, do you have a specific scenario that we can test ?
Regards

**Comment by ashishsabu** [comment]
Hello team,

Thank you for your response.
Issue occurred sporadically when I used customised bitmap image.
As I mentioned before in some cases after 4-5 login attempts the login
screen display the default MultiOTP bitmap image.

Regards,
Ashish Sabu

**Comment by multiOTP** [comment]
Hello Ashish,
Sorry, we were not able to reproduce your issue, do you have a specific scenario that we can test ?
Regards
