### ISSUE TITLE
Enable multiOTPC for specific RDP users.

### ISSUE THREAD

**Issue by emersonpfs** [multiOTP/multiOTPCredentialProvider#84]
Hi,
Is it possible to configure multiOTPC for specific local RDP accounts?
We have a scenario where all users access the server with their domain password, but we have some local accounts and these accounts have no password change policy, so we want to enable multiOTPC only for these users.
Do you have any setting like exclude_account? but who does the opposite? only activates the multiOTPC for the informed user?
Thanks

Best

**Comment by multiOTP** [comment]
Hello,
With the last version of multiOTP server (including the open source one), it's possible to define special "without_2fa" tokens.
Attribute without_2fa tokens to users that don't need authentication, and TOTP tokens to others.
If you are doing AD/LDAP sync, you can specify a group for "without_2fa" users, and another group for "TOTP" tokens.
Regards,
