### ISSUE TITLE
Failed to read registry setting values correctly.

### ISSUE THREAD

**Issue by khaisis** [multiOTP/multiOTPCredentialProvider#87]
Hi there.

The code in the following location doesn't seem to be working correctly.

It looks like you need to either find a pointer to the string in the settings array and compare for equality, or treat it as a string comparison function.

- readKeyValueInMultiOTPRegistry
- readRegistryValueString
{
	HKEY rootKeyValue = s_CONF_VALUES[conf_value].ROOT_KEY;

       ...

	if (hr == S_OK) {
		wcscpy_s(confKeyNameCLSID, 1024, confKeyName);
		if (confKeyName == (PWSTR)MULTIOTP_SETTINGS) {  <--- here (CONF_VALUE : CONF_PATH, Debug build, always false)
			wcscat_s(confKeyNameCLSID, 1024, clsid);
		}
   ...
}

**Comment by multiOTP** [comment]
Hello, thanks for your feedback but I don't have the same results as you.
It's true if the value you are looking for has MULTIOTP_SETTINGS in the s_CONF_VALUES array (for example CONF_PATH)
It's false if the value you are looking for has NOT MULTIOTP_SETTINGS in the s_CONF_VALUES array (for example CONF_RDP_PORT)

Best regards

**Comment by khaisis** [comment]
hello.
I tried to double-check the issue, but it's been a while and I don't remember the situation.

I'll get back to you if I check back later.
