### ISSUE TITLE
multiOTP credential provider doesn't work anymore

### ISSUE THREAD

**Issue by dominikjas** [multiOTP/multiOTPCredentialProvider#89]
Hello,

we are using the credential provider in a windows domain enviroment. The server and client is updated to the latest version and we have uninstalled all antivirus software. When we try to login we are getting this serror:
![grafik](https://user-images.githubusercontent.com/83553492/233643355-532dbd22-1691-46c9-84d5-1f2dee2a2d7f.png)
The serverlog is okay:
![grafik](https://user-images.githubusercontent.com/83553492/233643454-5205e6c8-6fd4-4054-b4bc-4622dbce6ae5.png)

- Server version: 5.9.5.5 / VM-006 
- Client version: 5.9.5.6

**Comment by Viach47** [comment]
Hello,
It looks like a case, I’v opened last week.
https://github.com/multiOTP/multiOTPCredentialProvider/issues/88
Could you check your server log (C:\MultiOTP\windows\log\multiotp.log) have it any records about “bad” login attempts?
And at “bad” user PC in multiOTP/config folder, you should be able to enable debug and log in multiotp.ini file.  Search and change the following entries:
•	debug=1
•	log=1
 Will it create log or not ?

**Comment by multiOTP** [comment]
Hello Dominik,
As you have contacted us directly for the commercial version of multiOTP server, we have unlinked the licence in order to allow a new installation of the server.
Regards,
