### ISSUE TITLE
Unable to uninstall

### ISSUE THREAD

**Issue by alisolutions** [multiOTP/multiOTPCredentialProvider#9]

**Comment by alisolutions** [comment]
I have uninstalled the setup from Control panel, but still I am getting MultiOTP Login option while login into the system. Please help.

**Comment by multiOTP** [comment]
Hello, can you please try to follow those steps :

launch the file multiOTPCredentialProvider-unregister.reg (you must have administrator access).
You can download the file here : https://github.com/multiOTP/multiOTPCredentialProvider/tree/ad97a4879e62df708a592d5381404e1307c45de6/installer

Let me know if it helps.

Have a nice day

Yann

**Comment by alisolutions** [comment]
I did that but it does not work. 
The strange thing is when I remove a file having name MultiOneTimePasswordCredentialProvider.dll file from Windows/System32 folder. It becomes remove. And when I try to reinstall it using your installer it does not install again. Please help.

My Second question is, why we are getting a new user with second-factor authentication, ideally we 2FA should be enabled on the existing user. Please help, working on that from the last couple of days.

**Comment by alisolutions** [comment]
It working. 
Please have a look at the following issue for the complete detail.
#10
