### ISSUE TITLE
multiOTPTimeoutUnlock Value

### ISSUE THREAD

**Issue by Deraj53** [multiOTP/multiOTPCredentialProvider#91]
I believe the README.md entry for this value is incorrect under the Technical Details section.

Is this timeout value counted from the last time 2fa was authenticated? Or from when the computer enters the locked state?

**Comment by multiOTP** [comment]
Hello,
thanks for the info we will correct the read-me as soon as possible.

The timeout is counted from the last time 2fa was authenticated.

Best regards
