### ISSUE TITLE
Credential Provider crash whenGlobal Protect from PaloAlto is used and cpus_logon is set to 3d

### ISSUE THREAD

**Issue by manuxio** [multiOTP/multiOTPCredentialProvider#94]
Hello,
credential provider crashes when used in conjuction with Global Protect Before Login VPN client.
CPUS_LOGON is set as 3d
Eventviewer logs the following error.

Nome dell'applicazione che ha generato l'errore: LogonUI.exe, versione: 10.0.19041.1, timestamp: 0xc08a5452
Nome del modulo che ha generato l'errore: multiOTPCredentialProvider.dll, versione: 5.9.6.1, timestamp: 0x645b9351
Codice eccezione: 0xc0000005
Offset errore 0x000000000002d430
ID processo che ha generato l'errore: 0x624
Ora di avvio dell'applicazione che ha generato l'errore: 0x01d9ca0764509fe3
Percorso dell'applicazione che ha generato l'errore: C:\Windows\system32\LogonUI.exe
Percorso del modulo che ha generato l'errore: C:\Windows\system32\multiOTPCredentialProvider.dll
ID segnalazione: c67af3aa-949f-4ae3-ad1e-1419ad63a2e9
Nome completo pacchetto che ha generato l'errore:
ID applicazione relativo al pacchetto che ha generato l'errore: 

How can we provide you best details in order to replicate the error and possibly get a fix?

Error occurs right after clicking Global Protect icon (within logon screen, no need to connect to any vpn)
Global Protect version: 6.1.4 - The command to enable Before Logon for Global Protect is: PanGPS.exe -registerplap (run within Global Protect installation path)
If you need to download the client I can provide it privately.

**Comment by multiOTP** [comment]
Hello,
Thanks for using our product. We understand the problem and we will try to reproduce it. We will let you know as soon as we have some news.

Best regards

**Comment by manuxio** [comment]
Hello,
any news on the issue?
Would it expedite any possible solution if we had a valid subscription?

**Comment by multiOTP** [comment]
Hello Manuxio,
The multiOTP Credential Provider product is purely open source and supported by community.
There is no subscription options multiOTP Credential Provider.
Regards,

**Comment by multiOTP** [comment]
When you set CPUS_LOGON to the value 3d, it means that you do not want multiOTP to be active for this scenario (login on the computer).
Can you please send us the installer to support(a)multiotp.com please.

Best regards

**Comment by multiOTP** [comment]
A new release is underway.
