### ISSUE TITLE
installer

### ISSUE THREAD

**Issue by D55ma** [multiOTP/multiOTPCredentialProvider#95]
"Launch the installer (in the installer directory) and configure the various parameters during the setup. "
, is it meant by the installer the .exe file? because its not launching.. i cant find the problem.
thanks in advance.

**Comment by multiOTP** [comment]
Hello,
The installer is available in every release, unzip the multiOTPCredentialProvider-x.x.x.x.zip file, and launch the multiOTPCredentialProvider-x.x.x.x.msi file in order to install it.
Regards,

**Comment by multiOTP** [comment]
Please re-open the ticket if you cannot launch the msi file.
Regards,
