### ISSUE TITLE
Binary download page is not updated to 5.9.6.1

### ISSUE THREAD

**Issue by yankaiqian** [multiOTP/multiOTPCredentialProvider#96]
Not a big issue, I found that it is still 5.9.5.6 on this page:
https://download.multiotp.net/credential-provider/

Please update it to the latest version (5.9.6.1), we can also download it from here now :
https://github.com/multiOTP/multiOTPCredentialProvider/releases/tag/5.9.6.1

**Comment by multiOTP** [comment]
Hello,
Sorry for the inconvenience, 5.9.6.1 is now on the download.multiotp.net website.
Thx for your feedabck, and we hope that our product helps you.
Regards,
