### ISSUE TITLE
Feature request: Login failure reason on OTP window

### ISSUE THREAD

**Issue by ashishsabu** [multiOTP/multiOTPCredentialProvider#97]
Is it feasible to show the cause of a login failure on the OTP window?

For instance:
1. If a user's account is locked due to multiple incorrect OTP attempts, is it viable to display a message on the OTP window stating - "User account is locked"  to indicate the reason?

Thanks, 
Regards, 
Ashish Sabu

**Comment by multiOTP** [comment]
Hello,
we have developped a beta version with this feature included. If you are interessted in testing it please contact us directly on support@multiotp.net

Best regards

**Comment by ashishsabu** [comment]
Hello team,

Sorry for the late reply.
Due to some personal issues I am unable to answer your queries.

Please let me know whether this functionality is added in release?

Thank you.

Regards,
Ashish Sabu

**Comment by ashishsabu** [comment]
Gentle reminder

**Comment by multiOTP** [comment]
Hello,
we have developped a beta version with this feature included. If you are interessted in testing it please contact us directly on support@multiotp.net

Best regards

**Comment by ashishsabu** [comment]
Hello team,

I have tested the functionality and it is working fine as expected.

Last time I did some mistakes in my testing.

Please let me know if you need any help.

Thank you.

Regards,.
Ashish sabu

**Comment by ashishsabu** [comment]
Hello team,

Is it possible to share the status of this feature request?

Whether it will be added in main release or only beta will be released??

Thanks & Regards,
Ashish Sabu

**Comment by multiOTP** [comment]
Hello,
it will be published in the next release probably on monday.

Best regards.

**Comment by ashishsabu** [comment]
Ok, thanks for the update.

**Comment by multiOTP** [comment]
Hello,
The version 5.9.8.0 has been released, and it contains this modification.
If you are happy with our project, don't hesitate to support our developement: [https://6co.ch/donate-multiotp/](https://6co.ch/donate-multiotp/)
Regards,

**Comment by ashishsabu** [comment]
Thank you, I will check it out.
