### ISSUE TITLE
Active Directory Group filtering not working

### ISSUE THREAD

**Issue by RetiredTurtle** [multiOTP/multiOTPCredentialProvider#99]
I've set 

`multiotp.exe -config ldap-in-group=”GrpMFAUsers”`

There are 2 users in this group and they can receive tokens correctly. But when I try to login non 2FA users, they will ask OTP too.

multiOTPWithout2FA parameter is set to 1 and it controls again user's OTP.
On server side I can see only GrpMFAUsers users for OTP login. 

When I enable debug, server returns 

```
2023-12-29 11:15:31	debug		Server-Client	Info: *ReadUserData server request for user2	0	SERVER
2023-12-29 11:15:31	warning		System	Error: database file C:\multiotp\users\user2.db for user user2 does not exist	0	SERVER
```

But credential provider shouldn't ask for this user. Because this user is not in OTP group. On server side web interface I can't see this user normally.
![error](https://github.com/multiOTP/multiOTPCredentialProvider/assets/155155748/63a25c85-a16b-4d04-bd84-569b4b14b502)

Also I've tried WithoutMFA group, synced, restarted servers but same result.

**Comment by multiOTP** [comment]
Hello,
the group you set for the LDAP sync is just used to tell multiOTP which groups to load in the user database.

When using the credential provider, all users must exists in multiOTP server. It means that user2 must exists in your multiOTP server even if it has no 2FA.

Simply create a user called user2 and choos the algorithm without2FA and you should be able to login without OTP.

Best regards

**Comment by RetiredTurtle** [comment]
Hello again. 
Users is already active directory user and multiotp credential provider installed RDP session server. Both separate servers. Multiotp main service is installed on domain controller. User1, user2, user3 and user4 are active directory users. There is no any issue on user1 and user4 when logging in with otp. User2 and user3 are in non2fa group. User1 and user4 are in with2fa group. All users present in active directory.

**Comment by multiOTP** [comment]
Hello,
As multiOTP Credential Provider is designed with security in mind, there is no possible IMPLICIT 2FA bypass for users. You MUST have all the users in multiOTP server. If you don't want to authentiicate with some users, these users MUST BE in the authentication server, and you can put the algorithm to without2fa for them.
Please note that you can also synchronized AD/LDAP users that you DON'T WANT TO ASK 2FA, using the **ldap-without2fa-in-group** option.
Regards,

**Comment by RetiredTurtle** [comment]
Hello again.
I'm attaching my current user-group list and multiotp server ini file values.
![multiotp-ini](https://github.com/multiOTP/multiOTPCredentialProvider/assets/155155748/94786b0d-9a9e-44dd-a761-abee7a39e74a)
![users-groups](https://github.com/multiOTP/multiOTPCredentialProvider/assets/155155748/9139acfc-74bf-4cc9-86f0-d93c5134e8fb)

**Comment by RetiredTurtle** [comment]
@multiOTP Thanks for your support. I think i found the problem.
I made a clean install server / rdp and active directory and rebuild test environment.
Results were same.

I realized server's multiotp.ini and credential manager's multiotp.ini files are different.
I've copied server's multiotp.ini file to credential manager's config folder, and then run ldap sync. wolaaa it works.

The problem is, credential manager doesn't sync all settings from server and it fails while querying.
When settings copied to credential manager's config location it works without any issue.
But I should create a task for RDP to copy ini file and then sync ldap data.

Can you confirm this?

**Comment by multiOTP** [comment]
Hello,
multiOTP open source is a 2FA server, and mnultiOTP Credential Provider is a client for this server.
You don't have to synchronize anything between the client and the server.
They are sharing a lot of codes, but the users must only be created/synced/configured on the server part.
You may be confused because multiOTP Credential Provider can also be used without a multiOTP server. In this special case, the multiOTP instance integrated inside multiOPT Credential Provider is handling the users directly.
To resume:
- if you are using multiOTP Credential Provider with a multiOTP server (open source or commercial), don't define any user on the multiOTP Credential Provider side, as it will act as a client of the server.
- if you want to use multiOTP Credential Provider alone, and only in this case, yes, you can create and configure users on the multiOTP Credential Provider side

I hope that it is clear like this.

Regards,

**Comment by RetiredTurtle** [comment]
I mean MultiOTP credential manager doesn't get any settings from server and fails when non-OTP users logged in.
